### ISSUE TITLE
Various "Cannot find module" on starting a new Docker image

### ISSUE THREAD

**Issue by michzimny** [up2university/multiparty-meeting#3]
When starting the latest Docker image misi/mm with image ID: 243eb2cd8f8b, from ca. 4 days ago, I'm getting the error below.

When getting back to an older image - ID: 3d076d3e22e3 from ca. 2 weeks ago, it's fine.

Could you please check what's wrong with the latest image?

```
Container starting up...
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './config/config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/opt/multiparty-meeting/server/server.js:7:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by michzimny** [comment]
@misi, could you please have a look?

It also happens for the latest image, built from https://github.com/misi/mm/tree/a324eca378d5c6cebb27c73d4dcfbad9e9fe6760

**Comment by misi** [comment]
I will check the difference between up2university/multiparty-meeting and misi/mm..
Sorry for the delay. Thanks for your patience.

**Comment by michzimny** [comment]
Just found an issue. This is because I haven't noticed you changes to directory structure (config/configs, cert/certs, etc.). But have another issue, will report in a moment.
